# Use the official MongoDB image from Docker Hub
FROM mongo:latest

# Set environment variables
ENV MONGO_INITDB_ROOT_USERNAME=""
ENV MONGO_INITDB_ROOT_PASSWORD=""

# Expose MongoDB default port
EXPOSE 27017
